port: 8091

server:
  type: Emby                        # Emby 或 Jellyfin
  addr: http://172.17.0.1:8096      # 媒体服务器地址
  auth: "YOUR_API_KEY_HERE"         # API Key

cache:
  enable: true                      # 是否启用 HTTPStrm 重定向内存缓存
  http_strm_ttl: 1m                 # 重定向缓存有效期

client:                             # 客户端过滤器
  enable: false                     # 是否启用客户端过滤器
  mode: BlackList                   # WhiteList (白名单) / BlackList (黑名单)
  list:                             # 名单列表 (包含匹配)
    - Fileball
    - Infuse

http_strm:
  enable: true                      # 开启
  disable_transcode: true           # 禁用转码
  resolve_strm_links: true          # 自动解析 302 (要服务端可以直接播放，解决Strm内容是局域网地址但是想要在公网之中播放开启了不用配置strm地址替换规则留空即可)
  alist_ua_passthrough: false       # 解析链接时是否携带客户端UA
  path_mappings:                    # strm地址替换规则
    - old: "http://127.0.0.1:12398"
      new: "https://openlist.com"

logging:
  verbose: false                    # 是否启用详细日志