port: 8091

server:
  type: Emby
  addr: http://localhost:8096
  auth: "YOUR_EMBY_API_KEY"

http_strm:
  enable: true
  disable_transcode: true
  resolve_strm_links: true  # 开启后自动解析 127.0.0.1
  path_mappings:
    - old: "http://127.0.0.1:12398"
      new: "https://openlist.com"

alist_strm:
  enable: true
  disable_transcode: true
  alist_host: "http://127.0.0.1:5244"
  alist_public_host: ""
  alist_token: "YOUR_ALIST_TOKEN"
  alist_ua_passthrough: false
  path_mappings:
    - old: "/mnt/aliyun"
      new: "/aliyun"