services:
  emby2alist:
    build:
      context: .
      network: host
    image: emby2alist:latest
    container_name: emby2alist
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yaml:/app/config.yaml